# path to zend project root
repository_root: "./"
# new release version (format "major.minor.patch", suffix must not be included if beta or candidate or alpha)
version: "5.0.0"
# build number (0-24 for beta (1-25), 25-49 for candidate (1-25), 50 for official, 51+ for alpha (1+))
build_number: "50"
# mainnet config
mainnet:
  # height for checkpoint (if empty, current last block is used)
  checkpoint_height: "1491300"
  # total transaction from genesis block up to checkpoint (can be found in "debug.log" file)
  total_transactions: "37913714"
# testnet config
testnet:
  # height for checkpoint (if empty, current last block is used)
  checkpoint_height: "1405200"
  # total transaction from genesis block up to checkpoint (can be found in "debug.log" file)
  total_transactions: "2337720"
# release date (format "%a, %d %b %Y", e.g. "Fri, 14 Apr 2023")
release_date: "Mon, 22 Jan 2024"
# approximated release height (mainnet)
approx_release_height: "1493670"
# weeks until deprecation
weeks_until_deprecation: "15"
# script steps flow
script_steps:
  # initialize_check_main_checked_out (sub)step
  initialize_check_main_checked_out:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # initialize_check_no_pending_changes (sub)step
  initialize_check_no_pending_changes:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # initialize_create_branch (sub)step
  initialize_create_branch:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # set_client_version step
  set_client_version:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: True
  # update_checkpoints step
  update_checkpoints:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_changelog step
  update_changelog:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_deprecation_height step
  update_deprecation_height:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # build_zend step
  build_zend:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_man_pages step
  update_man_pages:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_release_notes step
  update_release_notes:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: True
  # update_readme step
  update_readme:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # check_dependencies step
  check_dependencies:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
