# THIS IS A TEMPLATE FILE, FOR EXAMPLES ON ACTUAL RELEASES CHECK CONTENT OF configs/release_preparation_config-X.Y.Z.yaml FILES
# path to zend project root
repository_root: "./"
# new release version (format "major.minor.patch", suffix must not be included if beta or candidate or alpha)
version: ""
# build number (0-24 for beta (1-25), 25-49 for candidate (1-25), 50 for official, 51+ for alpha (1+))
build_number: ""
# mainnet config
mainnet:
  # height for checkpoint (if empty, current last block is used)
  checkpoint_height: ""
  # total transaction from genesis block up to checkpoint (can be found in "debug.log" file)
  total_transactions: ""
# testnet config
testnet:
  # height for checkpoint (if empty, current last block is used)
  checkpoint_height: ""
  # total transaction from genesis block up to checkpoint (can be found in "debug.log" file)
  total_transactions: ""
# release date (format "%a, %d %b %Y", e.g. "Mon, 2 Jan 2023")
release_date: ""
# approximated release height (mainnet)
approx_release_height: ""
# weeks until deprecation
weeks_until_deprecation: ""
# script steps flow
script_steps:
  # initialize_check_main_checked_out (sub)step
  initialize_check_main_checked_out:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # initialize_check_no_pending_changes (sub)step
  initialize_check_no_pending_changes:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # initialize_create_branch (sub)step
  initialize_create_branch:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # set_client_version step
  set_client_version:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_checkpoints step
  update_checkpoints:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_changelog step
  update_changelog:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_deprecation_height step
  update_deprecation_height:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # build_zend step
  build_zend:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_man_pages step
  update_man_pages:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_release_notes step
  update_release_notes:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # check_dependencies step
  check_dependencies:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
