# THIS IS A TEMPLATE FILE, FOR EXAMPLES ON ACTUAL RELEASES CHECK CONTENT OF prepare_release-X.Y.Z.yaml FILES
# path to zend project root
repository_root: "./"
# new release version (format "major.minor.patch", suffix must not be included if beta or candidate)
version: ""
# build number (1-24 for beta (1-24), 25-49 for candidate (1-25), 50 for official)
build: ""
# mainnet config
mainnet:
  # height for checkpoint (if empty, current last block is used)
  checkpoint_height: ""
  # total transaction from genesis block up to checkpoint (can be found in "debug.log" file)
  total_transactions: ""
# testnet config
testnet:
  # height for checkpoint (if empty, current last block is used)
  checkpoint_height: ""
  # total transaction from genesis block up to checkpoint (can be found in "debug.log" file)
  total_transactions: ""
# release date (format "%a, %d %b %Y", e.g. "Apr, 14 Fri 2023")
release_date: ""
# approximated release height (mainnet)
approx_release_height: ""
# weeks until deprecation
weeks_until_deprecation: ""
# previous version (format "major.minor.patch", build suffix must be included if beta or candidate)
previous_version: ""
# path to release notes file
release_notes_file: "./release-notes.md"
# script steps flow
script_steps:
  # set_client_version step
  set_client_version:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_checkpoints step
  update_checkpoints:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_changelog step
  update_changelog:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_deprecation_height step
  update_deprecation_height:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # build_zend step
  build_zend:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_man_pages step
  update_man_pages:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_release_notes step
  update_release_notes:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # update_readme step
  update_readme:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
